global:
   scrape_interval: 15s
scrape_configs:
   - job_name: "prometheus"
     honor_timestamps: true
     scrape_interval: 15s
     scrape_timeout: 10s
     metrics_path: /metrics
     scheme: http
     follow_redirects: true
     static_configs:
        - targets:
             - localhost:9090

   - job_name: "spring"
     metrics_path: "/actuator/prometheus"
     static_configs:
        - targets: ["dc-sb-prom:8080"]
        
   - job_name: "postgres"
     metrics_path: "/metrics"
     static_configs:
        - targets: ["postgres_metrics:9187"]
